package com.reconcilem.jdbc;

import com.reconcilem.core.model.MatchResult;
import com.reconcilem.core.model.MatchScore;
import com.reconcilem.core.model.ReconciliationRecord;
import com.reconcilem.core.model.ReconciliationResult;
import com.reconcilem.core.model.ReconciliationSummary;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

public class JdbcReconciliationResultRepository {

    private final JdbcTemplate jdbcTemplate;

    public JdbcReconciliationResultRepository(DataSource dataSource) {
        this(new JdbcTemplate(Objects.requireNonNull(dataSource, "DataSource must not be null")));
    }

    public JdbcReconciliationResultRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = Objects.requireNonNull(jdbcTemplate, "JdbcTemplate must not be null");
    }

    public void createSchema() {
        try {
            jdbcTemplate.execute("""
                    create table if not exists reconcilem_job_run (
                        run_id varchar(36) primary key,
                        job_name varchar(255) not null,
                        created_at timestamp not null,
                        source_count integer not null,
                        target_count integer not null,
                        matched_count integer not null,
                        possible_match_count integer not null,
                        unmatched_source_count integer not null,
                        unmatched_target_count integer not null
                    )
                    """);

            jdbcTemplate.execute("""
                    create table if not exists reconcilem_match_result (
                        id bigint generated by default as identity primary key,
                        run_id varchar(36) not null,
                        source_record_id varchar(255) not null,
                        target_record_id varchar(255),
                        decision varchar(50) not null,
                        total_score integer not null,
                        score_details clob,
                        foreign key (run_id) references reconcilem_job_run(run_id)
                    )
                    """);

            jdbcTemplate.execute("""
                    create table if not exists reconcilem_unmatched_record (
                        id bigint generated by default as identity primary key,
                        run_id varchar(36) not null,
                        record_side varchar(20) not null,
                        record_id varchar(255) not null,
                        record_source varchar(255) not null,
                        transaction_date date,
                        amount numeric(19, 4) not null,
                        currency varchar(20),
                        counterparty_name varchar(500),
                        reference varchar(500),
                        attributes clob,
                        foreign key (run_id) references reconcilem_job_run(run_id)
                    )
                    """);
        } catch (Exception ex) {
            throw new JdbcWriteException("Failed to create ReconcileM JDBC result tables", ex);
        }
    }

    public String save(String jobName, ReconciliationResult result) {
        Objects.requireNonNull(result, "Reconciliation result must not be null");

        String normalizedJobName = requireText(jobName, "Job name");
        String runId = UUID.randomUUID().toString();

        try {
            saveRun(runId, normalizedJobName, result.summary());
            saveMatches(runId, result.matched());
            saveMatches(runId, result.possibleMatches());
            saveMatches(runId, result.duplicateMatches());
            saveMatches(runId, result.conflictMatches());
            saveUnmatched(runId, "SOURCE", result.unmatchedSourceRecords());
            saveUnmatched(runId, "TARGET", result.unmatchedTargetRecords());
            return runId;
        } catch (Exception ex) {
            throw new JdbcWriteException("Failed to persist reconciliation result", ex);
        }
    }

    private void saveRun(String runId, String jobName, ReconciliationSummary summary) {
        jdbcTemplate.update("""
                insert into reconcilem_job_run (
                    run_id,
                    job_name,
                    created_at,
                    source_count,
                    target_count,
                    matched_count,
                    possible_match_count,
                    unmatched_source_count,
                    unmatched_target_count
                ) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                runId,
                jobName,
                Timestamp.from(Instant.now()),
                summary.sourceCount(),
                summary.targetCount(),
                summary.matchedCount(),
                summary.possibleMatchCount(),
                summary.unmatchedSourceCount(),
                summary.unmatchedTargetCount()
        );
    }

    private void saveMatches(String runId, List<MatchResult> matches) {
        for (MatchResult match : matches) {
            String targetRecordId = match.targetRecord() == null ? null : match.targetRecord().id();

            jdbcTemplate.update("""
                    insert into reconcilem_match_result (
                        run_id,
                        source_record_id,
                        target_record_id,
                        decision,
                        total_score,
                        score_details
                    ) values (?, ?, ?, ?, ?, ?)
                    """,
                    runId,
                    match.sourceRecord().id(),
                    targetRecordId,
                    match.decision().name(),
                    match.totalScore(),
                    formatScores(match.scores())
            );
        }
    }

    private void saveUnmatched(String runId, String side, List<ReconciliationRecord> records) {
        for (ReconciliationRecord record : records) {
            jdbcTemplate.update("""
                    insert into reconcilem_unmatched_record (
                        run_id,
                        record_side,
                        record_id,
                        record_source,
                        transaction_date,
                        amount,
                        currency,
                        counterparty_name,
                        reference,
                        attributes
                    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    runId,
                    side,
                    record.id(),
                    record.source(),
                    record.transactionDate(),
                    record.amount(),
                    record.currency(),
                    record.counterpartyName(),
                    record.reference(),
                    record.attributes().toString()
            );
        }
    }

    private String formatScores(List<MatchScore> scores) {
        return scores.stream()
                .map(score -> score.ruleName() + "=" + score.score() + ": " + score.explanation())
                .toList()
                .toString();
    }

    private String requireText(String value, String fieldName) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(fieldName + " must not be blank");
        }

        return value.trim();
    }
}
